-- Follow-up top-up migration after 20260324000400 may already be deployed.
-- Ensures each phoneme/position has at least 3 examples.
-- Idempotent: only inserts missing mappings and keeps existing data untouched.

begin;

with mappings(sound_code, position, word_text) as (
  values
    ('m', 'beginning', 'map'),
    ('m', 'beginning', 'moon'),
    ('m', 'beginning', 'mouse'),
    ('m', 'middle', 'lemon'),
    ('m', 'middle', 'summer'),
    ('m', 'middle', 'camel'),
    ('m', 'end', 'jam'),
    ('m', 'end', 'ham'),
    ('m', 'end', 'gum'),

    ('b', 'beginning', 'bat'),
    ('b', 'beginning', 'ball'),
    ('b', 'beginning', 'bike'),
    ('b', 'middle', 'rabbit'),
    ('b', 'middle', 'cabin'),
    ('b', 'middle', 'table'),
    ('b', 'end', 'tub'),
    ('b', 'end', 'cab'),
    ('b', 'end', 'web'),

    ('p', 'beginning', 'pig'),
    ('p', 'beginning', 'pen'),
    ('p', 'beginning', 'pan'),
    ('p', 'middle', 'apple'),
    ('p', 'middle', 'open'),
    ('p', 'middle', 'paper'),
    ('p', 'end', 'cup'),
    ('p', 'end', 'cap'),
    ('p', 'end', 'map'),

    ('h', 'beginning', 'hat'),
    ('h', 'beginning', 'house'),
    ('h', 'beginning', 'hand'),
    ('h', 'middle', 'behind'),
    ('h', 'middle', 'ahead'),
    ('h', 'middle', 'perhaps'),
    ('h', 'end', 'huh'),
    ('h', 'end', 'oh'),
    ('h', 'end', 'yeah'),

    ('æ', 'beginning', 'apple'),
    ('æ', 'beginning', 'animal'),
    ('æ', 'beginning', 'ankle'),
    ('æ', 'middle', 'rabbit'),
    ('æ', 'middle', 'cactus'),
    ('æ', 'middle', 'happy'),
    ('æ', 'end', 'cat'),
    ('æ', 'end', 'bat'),
    ('æ', 'end', 'map'),

    ('ɑ', 'beginning', 'octopus'),
    ('ɑ', 'beginning', 'olive'),
    ('ɑ', 'beginning', 'otter'),
    ('ɑ', 'middle', 'father'),
    ('ɑ', 'middle', 'taco'),
    ('ɑ', 'middle', 'pasta'),
    ('ɑ', 'end', 'spa'),
    ('ɑ', 'end', 'pa'),
    ('ɑ', 'end', 'bra'),

    ('ʌ', 'beginning', 'up'),
    ('ʌ', 'beginning', 'under'),
    ('ʌ', 'beginning', 'umbrella'),
    ('ʌ', 'middle', 'puppy'),
    ('ʌ', 'middle', 'butter'),
    ('ʌ', 'middle', 'sunny'),
    ('ʌ', 'end', 'cup'),
    ('ʌ', 'end', 'sun'),
    ('ʌ', 'end', 'mud'),

    ('ə', 'beginning', 'about'),
    ('ə', 'beginning', 'ago'),
    ('ə', 'beginning', 'aside'),
    ('ə', 'middle', 'banana'),
    ('ə', 'middle', 'sofa'),
    ('ə', 'middle', 'pencil'),
    ('ə', 'end', 'sofa'),
    ('ə', 'end', 'comma'),
    ('ə', 'end', 'zebra'),

    ('ɪ', 'beginning', 'igloo'),
    ('ɪ', 'beginning', 'insect'),
    ('ɪ', 'beginning', 'itch'),
    ('ɪ', 'middle', 'kitten'),
    ('ɪ', 'middle', 'window'),
    ('ɪ', 'middle', 'pillow'),
    ('ɪ', 'end', 'fish'),
    ('ɪ', 'end', 'big'),
    ('ɪ', 'end', 'pig'),

    ('i', 'beginning', 'eagle'),
    ('i', 'beginning', 'equal'),
    ('i', 'beginning', 'even'),
    ('i', 'middle', 'kiwi'),
    ('i', 'middle', 'pizza'),
    ('i', 'middle', 'teacher'),
    ('i', 'end', 'tree'),
    ('i', 'end', 'bee'),
    ('i', 'end', 'key'),

    ('ɛ', 'beginning', 'elephant'),
    ('ɛ', 'beginning', 'echo'),
    ('ɛ', 'beginning', 'exit'),
    ('ɛ', 'middle', 'pepper'),
    ('ɛ', 'middle', 'seven'),
    ('ɛ', 'middle', 'message'),
    ('ɛ', 'end', 'bed'),
    ('ɛ', 'end', 'red'),
    ('ɛ', 'end', 'head'),

    ('ʊ', 'beginning', 'hook'),
    ('ʊ', 'beginning', 'hood'),
    ('ʊ', 'beginning', 'wolf'),
    ('ʊ', 'middle', 'cookie'),
    ('ʊ', 'middle', 'pudding'),
    ('ʊ', 'middle', 'bullet'),
    ('ʊ', 'end', 'book'),
    ('ʊ', 'end', 'look'),
    ('ʊ', 'end', 'crook'),

    ('u', 'beginning', 'ooze'),
    ('u', 'beginning', 'oozy'),
    ('u', 'beginning', 'oodle'),
    ('u', 'middle', 'tooth'),
    ('u', 'middle', 'noodle'),
    ('u', 'middle', 'ruler'),
    ('u', 'end', 'blue'),
    ('u', 'end', 'shoe'),
    ('u', 'end', 'zoo'),

    ('e', 'beginning', 'acorn'),
    ('e', 'beginning', 'apron'),
    ('e', 'beginning', 'agent'),
    ('e', 'middle', 'rainbow'),
    ('e', 'middle', 'paper'),
    ('e', 'middle', 'bacon'),
    ('e', 'end', 'day'),
    ('e', 'end', 'play'),
    ('e', 'end', 'gray'),

    ('o', 'beginning', 'open'),
    ('o', 'beginning', 'oval'),
    ('o', 'beginning', 'ocean'),
    ('o', 'middle', 'robot'),
    ('o', 'middle', 'moment'),
    ('o', 'middle', 'focus'),
    ('o', 'end', 'go'),
    ('o', 'end', 'no'),
    ('o', 'end', 'so'),

    ('w', 'beginning', 'we'),
    ('w', 'beginning', 'water'),
    ('w', 'beginning', 'wagon'),
    ('w', 'middle', 'away'),
    ('w', 'middle', 'flower'),
    ('w', 'middle', 'coward'),
    ('w', 'end', 'cow'),
    ('w', 'end', 'snow'),
    ('w', 'end', 'how'),

    ('j', 'beginning', 'yellow'),
    ('j', 'beginning', 'yoyo'),
    ('j', 'beginning', 'yam'),
    ('j', 'middle', 'canyon'),
    ('j', 'middle', 'million'),
    ('j', 'middle', 'onion'),
    ('j', 'end', 'toy'),
    ('j', 'end', 'boy'),
    ('j', 'end', 'joy'),

    ('n', 'beginning', 'nose'),
    ('n', 'beginning', 'night'),
    ('n', 'beginning', 'nap'),
    ('n', 'middle', 'banana'),
    ('n', 'middle', 'tunnel'),
    ('n', 'middle', 'dinner'),
    ('n', 'end', 'sun'),
    ('n', 'end', 'moon'),
    ('n', 'end', 'rain'),

    ('ŋ', 'beginning', 'ngoni'),
    ('ŋ', 'beginning', 'ngoma'),
    ('ŋ', 'beginning', 'nguni'),
    ('ŋ', 'middle', 'finger'),
    ('ŋ', 'middle', 'hungry'),
    ('ŋ', 'middle', 'jungle'),
    ('ŋ', 'end', 'sing'),
    ('ŋ', 'end', 'ring'),
    ('ŋ', 'end', 'long'),

    ('k', 'beginning', 'cat'),
    ('k', 'beginning', 'kite'),
    ('k', 'beginning', 'cookie'),
    ('k', 'middle', 'baker'),
    ('k', 'middle', 'pocket'),
    ('k', 'middle', 'taco'),
    ('k', 'end', 'book'),
    ('k', 'end', 'back'),
    ('k', 'end', 'duck'),

    ('g', 'beginning', 'goat'),
    ('g', 'beginning', 'game'),
    ('g', 'beginning', 'gift'),
    ('g', 'middle', 'tiger'),
    ('g', 'middle', 'wagon'),
    ('g', 'middle', 'bigger'),
    ('g', 'end', 'bag'),
    ('g', 'end', 'dog'),
    ('g', 'end', 'frog'),

    ('f', 'beginning', 'fan'),
    ('f', 'beginning', 'fish'),
    ('f', 'beginning', 'fun'),
    ('f', 'middle', 'coffee'),
    ('f', 'middle', 'elephant'),
    ('f', 'middle', 'waffle'),
    ('f', 'end', 'leaf'),
    ('f', 'end', 'roof'),
    ('f', 'end', 'knife'),

    ('v', 'beginning', 'van'),
    ('v', 'beginning', 'vase'),
    ('v', 'beginning', 'village'),
    ('v', 'middle', 'seven'),
    ('v', 'middle', 'river'),
    ('v', 'middle', 'cover'),
    ('v', 'end', 'glove'),
    ('v', 'end', 'wave'),
    ('v', 'end', 'five'),

    ('s', 'beginning', 'sun'),
    ('s', 'beginning', 'sock'),
    ('s', 'beginning', 'sand'),
    ('s', 'middle', 'messy'),
    ('s', 'middle', 'pencil'),
    ('s', 'middle', 'castle'),
    ('s', 'end', 'bus'),
    ('s', 'end', 'ice'),
    ('s', 'end', 'house'),

    ('z', 'beginning', 'zoo'),
    ('z', 'beginning', 'zebra'),
    ('z', 'beginning', 'zipper'),
    ('z', 'middle', 'music'),
    ('z', 'middle', 'lizard'),
    ('z', 'middle', 'busy'),
    ('z', 'end', 'nose'),
    ('z', 'end', 'cheese'),
    ('z', 'end', 'rose'),

    ('t', 'beginning', 'top'),
    ('t', 'beginning', 'table'),
    ('t', 'beginning', 'tiger'),
    ('t', 'middle', 'water'),
    ('t', 'middle', 'butter'),
    ('t', 'middle', 'city'),
    ('t', 'end', 'cat'),
    ('t', 'end', 'hat'),
    ('t', 'end', 'boat'),

    ('d', 'beginning', 'dog'),
    ('d', 'beginning', 'door'),
    ('d', 'beginning', 'desk'),
    ('d', 'middle', 'ladder'),
    ('d', 'middle', 'cuddle'),
    ('d', 'middle', 'spider'),
    ('d', 'end', 'red'),
    ('d', 'end', 'bed'),
    ('d', 'end', 'road'),

    ('ʃ', 'beginning', 'shoe'),
    ('ʃ', 'beginning', 'sheep'),
    ('ʃ', 'beginning', 'shark'),
    ('ʃ', 'middle', 'ocean'),
    ('ʃ', 'middle', 'mushroom'),
    ('ʃ', 'middle', 'washing'),
    ('ʃ', 'end', 'fish'),
    ('ʃ', 'end', 'dish'),
    ('ʃ', 'end', 'bush'),

    ('ʒ', 'beginning', 'genre'),
    ('ʒ', 'beginning', 'zhuzh'),
    ('ʒ', 'beginning', 'gendarme'),
    ('ʒ', 'middle', 'vision'),
    ('ʒ', 'middle', 'measure'),
    ('ʒ', 'middle', 'treasure'),
    ('ʒ', 'end', 'beige'),
    ('ʒ', 'end', 'garage'),
    ('ʒ', 'end', 'camouflage'),

    ('ʧ', 'beginning', 'chair'),
    ('ʧ', 'beginning', 'cheese'),
    ('ʧ', 'beginning', 'chicken'),
    ('ʧ', 'middle', 'kitchen'),
    ('ʧ', 'middle', 'teacher'),
    ('ʧ', 'middle', 'watching'),
    ('ʧ', 'end', 'beach'),
    ('ʧ', 'end', 'peach'),
    ('ʧ', 'end', 'match'),

    ('ʤ', 'beginning', 'jam'),
    ('ʤ', 'beginning', 'jeep'),
    ('ʤ', 'beginning', 'jelly'),
    ('ʤ', 'middle', 'magic'),
    ('ʤ', 'middle', 'pigeon'),
    ('ʤ', 'middle', 'region'),
    ('ʤ', 'end', 'badge'),
    ('ʤ', 'end', 'bridge'),
    ('ʤ', 'end', 'edge'),

    ('θ', 'beginning', 'thumb'),
    ('θ', 'beginning', 'think'),
    ('θ', 'beginning', 'three'),
    ('θ', 'middle', 'author'),
    ('θ', 'middle', 'bathroom'),
    ('θ', 'middle', 'toothache'),
    ('θ', 'end', 'bath'),
    ('θ', 'end', 'teeth'),
    ('θ', 'end', 'moth'),

    ('ð', 'beginning', 'this'),
    ('ð', 'beginning', 'that'),
    ('ð', 'beginning', 'those'),
    ('ð', 'middle', 'mother'),
    ('ð', 'middle', 'feather'),
    ('ð', 'middle', 'brother'),
    ('ð', 'end', 'breathe'),
    ('ð', 'end', 'soothe'),
    ('ð', 'end', 'seethe'),

    ('l', 'beginning', 'lip'),
    ('l', 'beginning', 'lamp'),
    ('l', 'beginning', 'lion'),
    ('l', 'middle', 'yellow'),
    ('l', 'middle', 'salad'),
    ('l', 'middle', 'pillow'),
    ('l', 'end', 'ball'),
    ('l', 'end', 'milk'),
    ('l', 'end', 'shell'),

    ('r', 'beginning', 'red'),
    ('r', 'beginning', 'rabbit'),
    ('r', 'beginning', 'rain'),
    ('r', 'middle', 'carrot'),
    ('r', 'middle', 'cereal'),
    ('r', 'middle', 'parrot'),
    ('r', 'end', 'car'),
    ('r', 'end', 'bear'),
    ('r', 'end', 'star'),

    ('aɪ', 'beginning', 'ice'),
    ('aɪ', 'beginning', 'item'),
    ('aɪ', 'beginning', 'island'),
    ('aɪ', 'middle', 'tiger'),
    ('aɪ', 'middle', 'pilot'),
    ('aɪ', 'middle', 'spider'),
    ('aɪ', 'end', 'pie'),
    ('aɪ', 'end', 'sky'),
    ('aɪ', 'end', 'fly'),

    ('aʊ', 'beginning', 'owl'),
    ('aʊ', 'beginning', 'out'),
    ('aʊ', 'beginning', 'hour'),
    ('aʊ', 'middle', 'flower'),
    ('aʊ', 'middle', 'mountain'),
    ('aʊ', 'middle', 'cowboy'),
    ('aʊ', 'end', 'cow'),
    ('aʊ', 'end', 'now'),
    ('aʊ', 'end', 'how'),

    ('ɔɪ', 'beginning', 'oil'),
    ('ɔɪ', 'beginning', 'oyster'),
    ('ɔɪ', 'beginning', 'ointment'),
    ('ɔɪ', 'middle', 'toilet'),
    ('ɔɪ', 'middle', 'voyage'),
    ('ɔɪ', 'middle', 'annoying'),
    ('ɔɪ', 'end', 'boy'),
    ('ɔɪ', 'end', 'toy'),
    ('ɔɪ', 'end', 'joy'),

    ('oʊ', 'beginning', 'oat'),
    ('oʊ', 'beginning', 'open'),
    ('oʊ', 'beginning', 'oval'),
    ('oʊ', 'middle', 'robot'),
    ('oʊ', 'middle', 'moment'),
    ('oʊ', 'middle', 'focus'),
    ('oʊ', 'end', 'go'),
    ('oʊ', 'end', 'no'),
    ('oʊ', 'end', 'show')
),
upsert_words as (
  insert into public.words (text, reading_level, part_of_speech, syllables)
  select distinct
    m.word_text,
    1,
    'other'::public.part_of_speech,
    1
  from mappings m
  on conflict (text) do update
    set reading_level = least(public.words.reading_level, excluded.reading_level)
),
current_counts as (
  select
    ws.sound_id,
    ws.position,
    count(*)::int as existing_count,
    coalesce(max(ws.sequence_index), -1)::int as max_sequence_index
  from public.word_sounds ws
  group by ws.sound_id, ws.position
),
candidates as (
  select
    s.id as sound_id,
    m.position::public.sound_position as position,
    w.id as word_id,
    m.word_text,
    coalesce(cc.existing_count, 0) as existing_count,
    coalesce(cc.max_sequence_index, -1) as max_sequence_index
  from mappings m
  join public.sounds s on s.code = m.sound_code
  join public.words w on w.text = m.word_text
  left join current_counts cc
    on cc.sound_id = s.id
   and cc.position = m.position::public.sound_position
  left join public.word_sounds ws
    on ws.sound_id = s.id
   and ws.position = m.position::public.sound_position
   and ws.word_id = w.id
  where ws.id is null
),
ranked_candidates as (
  select
    c.sound_id,
    c.position,
    c.word_id,
    c.max_sequence_index,
    greatest(0, 3 - c.existing_count) as needed,
    row_number() over (
      partition by c.sound_id, c.position
      order by c.word_text
    ) as candidate_rank
  from candidates c
)
insert into public.word_sounds (word_id, sound_id, position, sequence_index)
select
  rc.word_id,
  rc.sound_id,
  rc.position,
  rc.max_sequence_index + rc.candidate_rank
from ranked_candidates rc
where rc.candidate_rank <= rc.needed
on conflict (word_id, sound_id, position, sequence_index) do nothing;

commit;
